name: Build SCTX-Converter for Termux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang g++ flatbuffers-compiler

    - name: Configure and Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SctxConverter-Termux-ARM64
        path: build/SctxConverter
